afmontage/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('logic.urls')),
]

logic/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('trailer/<str:trailer_id>/', views.action_list, name='action_list'),
    path('trailer/<str:trailer_id>/restpunt/<str:action_id>', views.action, name='action'),
    path('maak/restpunt/', views.create_action, name='create_action'),
    path('maak/trailer/', views.create_trailer, name='create_trailer'),
]

logic/models.py
from django.db import models

# Create your models here.
class Trailer(models.Model):
    id = models.CharField('ID', null=False, primary_key=True, unique=True, max_length=16)
    description = models.CharField('Beschrijving', max_length=256)

    def __str__(self):
        return self.id
    
class Action(models.Model):
    LOCATIONS = (
        ('T', 'Op de trailer'),
        ('P', 'In de restpuntenpallet'),
        ('N', 'Nvt.'),
    )

    trailer_id = models.ForeignKey(Trailer, on_delete=models.CASCADE, null=False)
    id = models.AutoField(primary_key=True)
    summary = models.CharField('Samenvatting', max_length=256)

    is_component_detached = models.BooleanField('Het gaat om een restpunt met los onderdeel', default=False)
    is_component_delivered = models.BooleanField('Het onderdeel is geleverd', default=False)
    is_component_correct_amount = models.BooleanField('Het onderdeel is beschikbaar in benodigde hoeveelheid', default=False)

    who_contacted = models.CharField('Wie is gecontacteerd?', max_length=64)
    result_contact = models.CharField('Resultaat van contact', max_length=256)
    expected_delivery_date = models.DateField('Verwachte leveringsdatum', null=True)

    location_component = models.CharField(choices=LOCATIONS, max_length=1)

    description_of_action = models.TextField('Beschrijving van handeling', null=False)
    reason_action = models.TextField('Reden waarom handeling in hal 4 plaats moet vinden', null=False)
    name_creator_action = models.CharField('Naam melder van restpunt', max_length=64, null=False)
    extra_info_action = models.TextField('Aanvullende informatie', null=False)

    def __str__(self):
        return self.summary

logic/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect

# Create your views here.
from . import models

def index(request):
    context = {'trailer_list': models.Trailer.objects.all()}
    return render(request, 'index.html', context)

def action_list(request, trailer_id):
    context = {'trailer': get_object_or_404(models.Trailer, id=trailer_id),'action_list': models.Action.objects.filter(trailer_id=trailer_id)}
    return render(request, 'actions.html', context)

def action(request, trailer_id, action_id):
    context = {'action': get_object_or_404(models.Action, id=action_id)}
    return render(request, 'action.html', context)

def create_action(request):
    if request.method == 'POST':

        try:
            trailer = models.Trailer.objects.get(id=request.POST['id'])
        except models.Trailer.DoesNotExist:
            return render(request, 'trailer_not_exist.html')
        
        if request.POST['delivery_date'] == '':
            delivery_date = None
        else:
            delivery_date = request.POST['delivery_date']

        action = models.Action(
            trailer_id = models.Trailer.objects.get(id=request.POST['id']),
            summary = request.POST['summary'],
            is_component_detached = 'detached' in request.POST,
            is_component_delivered = request.POST.get('delivered') == 'true',
            is_component_correct_amount = request.POST.get('correct_amount') == 'true',
            who_contacted = request.POST['who_contacted'],
            result_contact = request.POST['result_contact'],
            expected_delivery_date = delivery_date,
            location_component = request.POST['location'],
            description_of_action = request.POST['description'],
            reason_action = request.POST['reason'],
            name_creator_action = request.POST['creator'],
            extra_info_action = request.POST['info'],
        )

        action.save()

        return HttpResponseRedirect('/')

    return render(request, 'create_action.html')

def create_trailer(request):
    if request.method == 'POST':
        trailer = models.Trailer(id=request.POST['id'], description=request.POST['description'])

        trailer.save()
        
        return HttpResponseRedirect('/')

    return render(request, 'create_trailer.html')

logic/templates/action.html
{% extends "base.html" %}

{% block title %}{{ action.summary }} - Trailer {{ action.trailer_id }}{% endblock %}

{% block body %}
    <h1>{{ action.summary }} - Trailer {{ action.trailer_id }}</h1>

    {% if action.is_component_detached %}
        <p>Het gaat om een restpunt met los onderdeel.</p>
    {% else %}
        <p>Het gaat om een restpunt zonder los onderdeel.</p>
    {% endif %}

    <p>Is het onderdeel aanwezig: {% if action.is_component_delivered %}Ja{% else %}Nee{% endif%}</p>

    {% if action.is_component_correct_amount %}
        <p>Het onderdeel is aanwezig in benogdigde hoeveelheid.</p>
    {% endif %}

    {% if action.who_contacted %}
        <p>Wie is gecontacteerd: {{ action.who_contacted }}</p>
    {% endif %}

    {% if action.result_contact %}
        <p>Resultaat van contact: {{ action.result_contact }}</p>
    {% endif %}

    {% if action.expected_delivery_date %}
        <p>Verwachte leveringsdatum : {{ action.expected_delivery_date|date:"d-m-Y" }}</p>
    {% endif %}

    {% if action.location_component %}
        <p>Locatie van onderdeel: {{ action.get_location_component_display }}</p>
    {% endif %}

    {% if action.description_of_action %}
        <p>Beschrijving van handeling: {{ action.description_of_action }}</p>
    {% endif %}

    {% if action.reason_action %}
        <p>Reden waarom handeling in hal 4 plaats moet vinden: {{ action.reason_action }}</p>
    {% endif %}

    {% if action.name_creator_action %}
        <p>Naam melder van restpunt: {{ action.name_creator_action }}
    {% endif %}

    {% if action.extra_info_action %}
        <p>Aanvullende informatie: {{ action.extra_info_action }}
    {% endif %}
{% endblock%}

logic/templates/actions.html
{% extends "base.html" %}

{% block title %}Trailer {{ trailer.id }}{% endblock %}

{% block body %}
    <h1>Trailer {{ trailer.id }}</h1>
    <p>{{ trailer.description }}</p>
    <ul>
        {% if action_list %}
        {% for action in action_list %}
        <li><a href="{% url 'action' action.trailer_id action.id %}">{{ action.id }} - {{ action.summary }}</a></li>
        {% endfor %}
        {% else %}
        <p>Er zijn geen restpunten geregisteerd op deze trailer.</p>
        {% endif %}
    </ul>
{% endblock %}

logic/templates/base.html
<!DOCTYPE html>
<html lang="nl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav style="text-align: end;">
        <a href="{% url 'create_trailer' %}">Nieuwe trailer</a>
        <a href="{% url 'create_action' %}">Nieuw restpunt</a>
        <a href="{% url 'index' %}">Home</a>
    </nav>
    {% block body %}{% endblock %}
</body>
</html>

logic/templates/create_action.html
{% extends "base.html" %}

{% block title %}Maak nieuw restpunt{% endblock %}

{% block body %}
    <h1>Maak nieuw restpunt</h1>

    <form method="POST">
        {% csrf_token %}

        <label for="id">Trailer nummer:</label>
        <input type="number" name="id" id="id" required><br><br>

        <label for="summary">Geef een korte samenvatting van dit restpunt:</label>
        <input type="text" name="summary" id="summary" maxlength="256" required><br>

        <p>Gaat het om een restpunt met of zonder los onderdeel?</p>
        <label>
            <input type="radio" name="detached" value="true" onclick="document.getElementById('with-loose-cont').style.display = 'block';"> Met los onderdeel
        </label><br>
        <label>
            <input type="radio" name="detached" value="false" onclick="document.getElementById('with-loose-cont').style.display = 'none';"> Zonder los onderdeel
        </label><br>

        <div id="with-loose-cont" style="display: none;">
            <p>Is het onderdeel aanwezig?</p>
            <label>
                <input type="radio" name="delivered" value="true" onclick="document.getElementById('contact-cont').style.display = 'none';document.getElementById('delivered-cont').style.display = 'block';document.getElementById('who_contacted').required = false;document.getElementById('result_contact').required = false;document.getElementById('delivery_date').required = false;"> Ja
            </label><br>
            <label>
                <input type="radio" name="delivered" value="false" onclick="document.getElementById('contact-cont').style.display = 'block';document.getElementById('delivered-cont').style.display = 'none';document.getElementById('location-cont').style.display = 'none';document.getElementById('who_contacted').required = true;document.getElementById('result_contact').required = true;document.getElementById('delivery_date').required = true;"> Nee
            </label><br>

            <div id='delivered-cont' style="display: none;">
                <p>Is het onderdeel in correcte hoeveelheid aanwezig?</p>
                <label>
                    <input type="radio" name="correct_amount" value="true" onclick="document.getElementById('contact-cont').style.display = 'none';document.getElementById('location-cont').style.display = 'block';"> Ja
                </label><br>
                <label>
                    <input type="radio" name="correct_amount" value="false" onclick="document.getElementById('contact-cont').style.display = 'block';document.getElementById('location-cont').style.display = 'block';document.getElementById('who_contacted').required = true;document.getElementById('result_contact').required = true;document.getElementById('delivery_date').required = true;"> Nee
                </label><br><br>
            </div>

            <div id="contact-cont" style="display: none;">
                <label for="who_contacted">Wie is gecontacteerd?</label>
                <input type="text" name="who_contacted" id="who_contacted" maxlength="64" ><br><br>

                <label for="result_contact">Wat is de uitkomst van dit contact:</label>
                <input type="text" name="result_contact" id="result_contact" maxlength="256"><br><br>

                <label for="delivery_date">Wat is de verwachte leveringsdatum:</label>
                <input type="date" name="delivery_date" id="delivery_date"><br><br>
            </div>
            
            <div id="location-cont" style="display: none;">
                <label for="location">Wat is de locatie van het onderdeel:</label>
                <select name="location" id="location">
                    <option value="T">Op de trailer</option>
                    <option value="P">In de restpuntenpallet</option>
                    <option value="N">Nvt.</option>
                </select><br>
            </div>
        </div>
        
        <br><label for="description">Welke bewerking moet er worden gedaan door Trailer compleet:</label><br>
        <textarea name="description" id="description" required></textarea><br><br>

        <label for="reason">Geef de reden waarom de bewerking in Trailer compleet plaats moet vinden i.p.v. De afmontage:</label><br>
        <textarea name="reason" id="reason" required></textarea><br><br>

        <label for="creator">Naam melder:</label>
        <input type="text" name="creator" id="creator" maxlength="64" required><br><br>

        <label for="info">Aanvullende informatie:</label><br>
        <textarea name="info" id="info" required></textarea><br><br>

        <button type="submit">Aanmaken</button>
    </form>
{% endblock %}

logic/templates/create_trailer.html
{% extends "base.html" %}

{% block title %}Maak nieuwe trailer{% endblock %}

{% block body %}
    <h1>Maak nieuwe trailer</h1>

    <form action="/maak/trailer/" method="post">
        {% csrf_token %}
        <label for="id">Trailer nummer:</label><br>
        <input type="text" name="id" required maxlength="16"><br><br>
        <label for="description">Beschrijving:</label><br>
        <input type="text" name="description" required maxlength="256"><br><br>
        <input type="submit" value="Verstuur" name="submit">
    </form>
{% endblock %}

logic/templates/index.html
{% extends "base.html" %}

{% block title %}Trailers{% endblock %}

{% block body %}
    <h1>Trailers</h1>
    <ul>
        {% if trailer_list %}
        {% for trailer in trailer_list %}
        <li><a href="{% url 'action_list' trailer.id %}">{{ trailer.id }} - {{ trailer.description }}</a></li>
        
        {% endfor %}
        {% else %}
        <p>Er zijn geen trailers beschikbaar om weer te geven.</p>
        {% endif %}
    </ul>
{% endblock %}

logic/templates/trailer_not_exist.html
{% extends "base.html" %}

{% block title %}Trailer bestaat niet{% endblock %}

{% block body %}
    <h1>Kan restpunt niet maken</h1>
    <p>Omdat trailer niet bestaat. Klopt het trailernummer?</p>
{% endblock %}